# Generated by Django 5.2.1 on 2025-05-17 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "official_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                ("subregion", models.CharField(blank=True, max_length=255, null=True)),
                ("independent", models.BooleanField(blank=True, null=True)),
                ("google_maps", models.URLField(blank=True, null=True)),
                ("openstreetmap", models.URLField(blank=True, null=True)),
                (
                    "capital_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("capital_lat", models.FloatField(blank=True, null=True)),
                ("capital_lng", models.FloatField(blank=True, null=True)),
                ("flag_png", models.URLField(blank=True, null=True)),
                ("flag_svg", models.URLField(blank=True, null=True)),
                ("flag_alt", models.CharField(blank=True, max_length=255, null=True)),
                ("coat_png", models.URLField(blank=True, null=True)),
                ("coat_svg", models.URLField(blank=True, null=True)),
                ("borders", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("probability", models.FloatField()),
                ("request_count", models.PositiveIntegerField(default=1)),
                ("last_accessed_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="core.country",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "country")},
            },
        ),
    ]
